name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          npm run deploy
          echo "Artifact URL: $ARTIFACT_URL"
          echo "Deployment Payload: $DEPLOYMENT_PAYLOAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
